### ISSUE TITLE
Manca README con descrizione e link a editor... 

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#32]
Ciao @Francesca1996. 
Riesci a integrare nella prossima pull request il file README che dicevamo? Uno per ogni cartellina di esercizi in p5.js (es. qui https://github.com/dsii-2020-unirsm/archive/tree/master/Francesca1996/P5/10PRINT/10_print_variazione_1 )
Se vuoi anche metterne uno di indice (es. nella cartella p5.js qui https://github.com/dsii-2020-unirsm/archive/tree/master/Francesca1996/P5/10PRINT ) con tutti raccolti e indicizzati in un unico file benvenga. 
Grazie mille buon lavoro.

**Comment by Fupete** [comment]
Sistema anche la cartella ExP5 che non si capisce che uso ha. ;-)

**Comment by Fupete** [comment]
@Francesca1996 nella pull request appena accettata hai risolto anche i contenuti di questa issue?

**Comment by Francesca1996** [comment]
Ho modificato il README.md descrivendo meglio cosa contiene la cartella ExP5
