### ISSUE TITLE
Manca README...

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#34]
Ciao @angelicazanibellato 
Riesci a integrare nella prossima pull request il file README che dicevamo? Uno per ogni cartellina di esercizi in p5.js (https://github.com/dsii-2020-unirsm/archive/tree/master/angelicazanibellato/Esercizi%20p5/NOISE/noise )
Se vuoi anche metterne uno di indice (es. nella cartella p5.js qui https://github.com/dsii-2020-unirsm/archive/tree/master/angelicazanibellato/Esercizi%20p5 ) con tutti raccolti e indicizzati in un unico file benvenga. O divisi per argomento nelle sottocartelle.
Grazie mille buon lavoro.

**Comment by angelicazanibellato** [comment]
https://github.com/dsii-2020-unirsm/archive/pull/50

**Comment by Fupete** [comment]
C'è un conflitto nella pull request sul file readme di Close Reading. 
Oggi in classe vediamo quale è e come risolvere. Per ora non posso fare Merge e quindi Chiudere questa Issue. A dopo.
