### ISSUE TITLE
Documentazione e README

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#35]
Ciao @benedettb 
Riesci a integrare nella prossima pull request il file README che dicevamo? Uno per ogni cartellina di esercizi in p5.js (es. https://github.com/dsii-2020-unirsm/archive/tree/master/benedettb/p5/es1_giochi_senza_frontiere )
Se vuoi anche metterne uno di indice (es. nella cartella p5.js qui https://github.com/dsii-2020-unirsm/archive/tree/master/benedettb/p5 ) con tutti raccolti e indicizzati in un unico file benvenga. 
Grazie mille buon lavoro.

**Comment by benedettb** [comment]
risolto
https://github.com/dsii-2020-unirsm/archive/pull/65
