### ISSUE TITLE
Aggiungi preview output, sistema link... 

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#39]
Ciao @ileniab puoi aggiungere una preview/immagine nel file README dell'output (per ogni esercizio che farai)? 

Magari anche un file README di indice nelle cartelle superiori... 

Per il link all'editor lascialo esplicito, non chiuso dentro il "+". 

Grazie mille.

**Comment by ileniab** [comment]
https://github.com/dsii-2020-unirsm/archive/pull/52
