### ISSUE TITLE
Naming README.md e varie... 

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#40]
Ciao @mgabriella, 

in questa cartella c'è un errore di naming, il file si dovrebbe chiamare README.md ... 

Dovresti inoltre mettere singoli README.md anche dentro tutti gli esercizi così che se arrivo direttamente a quella cartella e/o scarico direttamente quel solo esercizio ho comunque il "racconto"/documentazione di cosa sia. 

Grazie mille.

**Comment by mgabriella** [comment]
salve professore,
ho fatto come richiesto.
Ho inserito i README.md in tutte le cartelle degli esercizi e ho descritto cosa rappresentavano.

**Comment by mgabriella** [comment]
Salve professore,
ho sistemato i README.md dentro le cartelle di ogni esercizio
le allego il link della pull request. Grazie
https://github.com/dsii-2020-unirsm/archive/pull/64#issue-403899477
