### ISSUE TITLE
Cartelline... 

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#41]
Ciao @peterbaru 

Dai una sistemata alle tue cartelle. 
I file README dovrebbero stare allo stesso livello del codice, non nella cartellina superiore. Così se scarico quel codice ho direttamente anche il suo README/Leggimi... 

Raggrupperei poi tutti i codici in un'unica cartellina superiore (es. p5.js no?) Poi se vuoi sotto puoi dividere in sottocartelle per tema (noise, modulo, ...) e/o esercizio ma dalla root folder forse potrebbe intanto essercene una sola... 

Grazie

**Comment by Fupete** [comment]
Ah, dimenticavo, aggiungi anche una immagine preview di ogni output per cada README.md...

**Comment by peterbaru** [comment]
https://github.com/dsii-2020-unirsm/archive/pull/51 caricamento esercizi e correzione iusses
