### ISSUE TITLE
Nome file e inserimento output preview + pdf

### ISSUE THREAD

**Issue by Fupete** [dsii-2020-unirsm/archive#42]
Ciao @Angelica147 

Eccola la prima issue anche per te ;-) 

Ti pregherei di correggere l'estenzione del file README in questa cartella https://github.com/dsii-2020-unirsm/archive/tree/master/Angelica147/Esercizi%20p5/Random_parole (È md non dm).

Inserisci poi per tutti gli esercizi p5.js anche un'anteprima immagine dell'output nel file README. 

Magari crea un README indice nella cartellina superiore che più avanti ci aiuterà a navigare nei singoli lavori. 

Ultima cosa i file PDF, le analisi devono essere file md grazie.

**Comment by Angelica147** [comment]
Ok, grazie mille!

**Comment by Angelica147** [comment]
https://github.com/dsii-2020-unirsm/archive/pull/48 caricamento esercizi e correzioni issues
