### ISSUE TITLE
Issue per variazione 10PRINT

### ISSUE THREAD

**Issue by eleonoradfr** [dsii-2020-unirsm/archive#88]
@Fupete 
Qui (https://github.com/eleonoradfr/archive/tree/master/eleonoradfr/10PRINT/p5/01_variazione) ho caricato la mia prima variazione di 10PRINT (ancora poco interessante) che avevo scritto partendo dalla versione creata da Daniel Shiffman in p5 (https://www.youtube.com/watch?v=bEyTZ5ZZxZs). Avevo compreso più facilmente il codice seguendo il suo video. Posso continuare a costruire la mia variazione da questo codice o riparto dalla versione del libro?

**Comment by Fupete** [comment]
Procedi come meglio credi. 
Individua le caratteristiche di 10 print (ripetizione, estrazione casuale, ...) e crea un tuo algoritmo che sia raccontabile come variazione significativa di 10 print. Partendo da uno di questi, da quello mio sull'editor o scrivendone uno terzo. Procedi come credi.
